// Code generated by MockGen. DO NOT EDIT.
// Source: src/manager/order/order.go

// Package mock_order is a generated GoMock package.
package mock_order

import (
	context "context"
	reflect "reflect"

	models "github.com/MultiBanker/broker/src/models"
	selector "github.com/MultiBanker/broker/src/models/selector"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderer is a mock of Orderer interface.
type MockOrderer struct {
	ctrl     *gomock.Controller
	recorder *MockOrdererMockRecorder
}

// MockOrdererMockRecorder is the mock recorder for MockOrderer.
type MockOrdererMockRecorder struct {
	mock *MockOrderer
}

// NewMockOrderer creates a new mock instance.
func NewMockOrderer(ctrl *gomock.Controller) *MockOrderer {
	mock := &MockOrderer{ctrl: ctrl}
	mock.recorder = &MockOrdererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderer) EXPECT() *MockOrdererMockRecorder {
	return m.recorder
}

// NewOrder mocks base method.
func (m *MockOrderer) NewOrder(ctx context.Context, order *models.Order) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOrder", ctx, order)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewOrder indicates an expected call of NewOrder.
func (mr *MockOrdererMockRecorder) NewOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOrder", reflect.TypeOf((*MockOrderer)(nil).NewOrder), ctx, order)
}

// OrderByID mocks base method.
func (m *MockOrderer) OrderByID(ctx context.Context, id string) (models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderByID", ctx, id)
	ret0, _ := ret[0].(models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderByID indicates an expected call of OrderByID.
func (mr *MockOrdererMockRecorder) OrderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderByID", reflect.TypeOf((*MockOrderer)(nil).OrderByID), ctx, id)
}

// Orders mocks base method.
func (m *MockOrderer) Orders(ctx context.Context, paging *selector.Paging) ([]*models.Order, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Orders", ctx, paging)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Orders indicates an expected call of Orders.
func (mr *MockOrdererMockRecorder) Orders(ctx, paging interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Orders", reflect.TypeOf((*MockOrderer)(nil).Orders), ctx, paging)
}

// OrdersByReferenceID mocks base method.
func (m *MockOrderer) OrdersByReferenceID(ctx context.Context, referenceID string) ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersByReferenceID", ctx, referenceID)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersByReferenceID indicates an expected call of OrdersByReferenceID.
func (mr *MockOrdererMockRecorder) OrdersByReferenceID(ctx, referenceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersByReferenceID", reflect.TypeOf((*MockOrderer)(nil).OrdersByReferenceID), ctx, referenceID)
}

// PartnerOrder mocks base method.
func (m *MockOrderer) PartnerOrder(ctx context.Context, marketCode, referenceID string) ([]*models.PartnerOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PartnerOrder", ctx, marketCode, referenceID)
	ret0, _ := ret[0].([]*models.PartnerOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PartnerOrder indicates an expected call of PartnerOrder.
func (mr *MockOrdererMockRecorder) PartnerOrder(ctx, marketCode, referenceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PartnerOrder", reflect.TypeOf((*MockOrderer)(nil).PartnerOrder), ctx, marketCode, referenceID)
}

// UpdateMarketOrder mocks base method.
func (m *MockOrderer) UpdateMarketOrder(ctx context.Context, req models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMarketOrder", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMarketOrder indicates an expected call of UpdateMarketOrder.
func (mr *MockOrdererMockRecorder) UpdateMarketOrder(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMarketOrder", reflect.TypeOf((*MockOrderer)(nil).UpdateMarketOrder), ctx, req)
}

// UpdateOrder mocks base method.
func (m *MockOrderer) UpdateOrder(ctx context.Context, order *models.Order) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, order)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrdererMockRecorder) UpdateOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderer)(nil).UpdateOrder), ctx, order)
}

// UpdatePartnerOrder mocks base method.
func (m *MockOrderer) UpdatePartnerOrder(ctx context.Context, req models.PartnerOrder) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePartnerOrder", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePartnerOrder indicates an expected call of UpdatePartnerOrder.
func (mr *MockOrdererMockRecorder) UpdatePartnerOrder(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePartnerOrder", reflect.TypeOf((*MockOrderer)(nil).UpdatePartnerOrder), ctx, req)
}
