// Package users GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package users

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auto": {
            "get": {
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "list car product",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auto"
                ],
                "summary": "list car product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pagination limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pagination skip",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ListAuto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auto/{sku}": {
            "get": {
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "get car product",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auto"
                ],
                "summary": "get car product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sku",
                        "name": "sku",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Auto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/brokers/markets/login": {
            "post": {
                "description": "Авторизация маркета",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market"
                ],
                "summary": "Авторизация маркета",
                "parameters": [
                    {
                        "description": "body",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/brokers/markets/logout": {
            "get": {
                "description": "выход с авторизации маркета",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Market"
                ],
                "summary": "выход с авторизации маркета",
                "responses": {}
            }
        },
        "/api/v1/brokers/offers": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение офферов по заказу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Offers"
                ],
                "summary": "Получение офферов по заказу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.OffersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Offer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/brokers/orders/{reference_id}/partners": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получение заказов по reference_id",
                "tags": [
                    "Orders"
                ],
                "summary": "Получение заказов по reference_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "reference id of the order",
                        "name": "reference_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Order"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orders": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создание нового заказа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Создание нового заказа",
                "parameters": [
                    {
                        "description": "body",
                        "name": "market",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MarketOrderRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BrokerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orders/markets": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновление заказа по решению клиента",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Обновление заказа по решению клиента",
                "parameters": [
                    {
                        "description": "body",
                        "name": "market",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMarketOrderRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/partners/login": {
            "post": {
                "description": "Авторизация партнера",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Partner"
                ],
                "summary": "Авторизация партнера",
                "parameters": [
                    {
                        "description": "body",
                        "name": "auth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/partners/logout": {
            "get": {
                "description": "выход авторизации партнера",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Partner"
                ],
                "summary": "выход авторизации партнера",
                "responses": {}
            }
        },
        "/api/v1/partners/orders/": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновление заказа по решению партнера",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Обновление заказа по решению партнера",
                "parameters": [
                    {
                        "description": "body",
                        "name": "market",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.OrderPartnerUpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/application/": {
            "post": {
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "user application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user application",
                "parameters": [
                    {
                        "description": "add car",
                        "name": "auto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserApplication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/application/{id}": {
            "get": {
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "user application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserApplication"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiTokenAuth": []
                    }
                ],
                "description": "user application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "application id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/auth/signin/phone": {
            "post": {
                "description": "Аутентифицирует пользователя по номеру телефона",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Аутентификация по номеру телефона",
                "parameters": [
                    {
                        "description": "Данные для быстрой аутентификации",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignInByPhone"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NewJWTTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/auth/signout": {
            "delete": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Удаляет JWT токен в cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Завершает сессию пользователя, удаляя JWT токен",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Токен аутентификации",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/api/v1/users/auth/signup": {
            "post": {
                "description": "Регистрирует пользователя в ССО",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации пользователя",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SignUp"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/recovery/phone": {
            "put": {
                "description": "Отправляет OTP на указанный номер телефона для восстановления пароля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Отправка OTP на указанный номер телефона для восстановления пароля",
                "parameters": [
                    {
                        "description": "Данные для восстановления пароля",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RecoveryPhone"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/recovery/phone/otp": {
            "put": {
                "description": "Проверяет OTP при восстановлении пароля",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Валидация OTP по номеру телефона",
                "parameters": [
                    {
                        "description": "Данные для валидации OTP",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RecoveryPhoneOTP"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/verify/phone": {
            "put": {
                "description": "Отправляет OTP на указанный номер телефона для верификации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "verify"
                ],
                "summary": "Отправка OTP на указанный номер телефона для верификации",
                "parameters": [
                    {
                        "description": "Данные для верификации телефона",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyPhone"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "410": {
                        "description": "Gone",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/verify/phone/otp": {
            "put": {
                "description": "Проверяет OTP при верификации номера телефона и выдает JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "verify"
                ],
                "summary": "Валидация OTP по номеру телефона",
                "parameters": [
                    {
                        "description": "Данные для валидации OTP",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyPhoneOTP"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.NewJWTTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httperrors.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BrokerResponse": {
            "type": "object",
            "properties": {
                "reference_id": {
                    "type": "string"
                }
            }
        },
        "dto.FIO": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "Jon"
                },
                "lastName": {
                    "type": "string",
                    "example": "Bones"
                },
                "middleName": {
                    "type": "string",
                    "example": "Jones"
                }
            }
        },
        "dto.ListAuto": {
            "type": "object",
            "properties": {
                "autos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Auto"
                    }
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "dto.Login": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.MarketOrderRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/models.Address"
                },
                "amount": {
                    "type": "string",
                    "example": "5000"
                },
                "channel": {
                    "type": "string",
                    "example": "airba_web"
                },
                "cityId": {
                    "type": "string",
                    "example": "050000"
                },
                "customer": {
                    "$ref": "#/definitions/models.Customer"
                },
                "goods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Goods"
                    }
                },
                "isDelivery": {
                    "type": "boolean",
                    "example": true
                },
                "loanLength": {
                    "type": "integer",
                    "example": 12
                },
                "paymentMethod": {
                    "type": "string",
                    "example": "annuity"
                },
                "paymentPartners": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PaymentPartners"
                    }
                },
                "productType": {
                    "type": "string",
                    "example": "installment"
                },
                "redirectUrl": {
                    "type": "string",
                    "example": "https://airba.kz/order/ok"
                },
                "systemCode": {
                    "type": "string",
                    "example": "oms"
                },
                "verificationId": {
                    "type": "string",
                    "example": "dsad12"
                },
                "verificationSmsCode": {
                    "type": "string",
                    "example": "12321"
                },
                "verificationSmsDateTime": {
                    "type": "string",
                    "example": "12.12.2020"
                }
            }
        },
        "dto.NewJWTTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "tdid": {
                    "type": "string"
                }
            }
        },
        "dto.OffersRequest": {
            "type": "object",
            "properties": {
                "goods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Goods"
                    }
                }
            }
        },
        "dto.OrderPartnerUpdateRequest": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/dto.FIO"
                },
                "offers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Offers"
                    }
                },
                "referenceId": {
                    "type": "string",
                    "example": "1"
                },
                "state": {
                    "type": "string",
                    "example": "order_confirmed"
                },
                "stateTitle": {
                    "type": "string",
                    "example": "order_confirmed"
                }
            }
        },
        "dto.RecoveryPhone": {
            "type": "object",
            "properties": {
                "phone": {
                    "description": "Номер телефона для восстановления",
                    "type": "string"
                }
            }
        },
        "dto.RecoveryPhoneOTP": {
            "type": "object",
            "properties": {
                "otp": {
                    "description": "One-Time-Password отправленный по СМС",
                    "type": "string"
                },
                "password": {
                    "description": "Новый пароль пользователя",
                    "type": "string"
                },
                "phone": {
                    "description": "Номер телефона для восстановления",
                    "type": "string"
                }
            }
        },
        "dto.SignInByPhone": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "Пароль для аутентификации",
                    "type": "string"
                },
                "phone": {
                    "description": "Номер телефона для аутентификации",
                    "type": "string"
                }
            }
        },
        "dto.SignUp": {
            "type": "object",
            "properties": {
                "first_name": {
                    "description": "Имя пользователя",
                    "type": "string"
                },
                "last_name": {
                    "description": "Фамилия пользователя",
                    "type": "string"
                },
                "password": {
                    "description": "Пароль пользователя",
                    "type": "string"
                },
                "patronymic": {
                    "description": "Отчество пользователя",
                    "type": "string"
                },
                "phone": {
                    "description": "Номер телефона пользователя",
                    "type": "string"
                }
            }
        },
        "dto.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "response_token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateMarketOrderRequest": {
            "type": "object",
            "properties": {
                "loanLength": {
                    "type": "string"
                },
                "productCode": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "referenceId": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "stateTitle": {
                    "type": "string"
                }
            }
        },
        "dto.UserApplication": {
            "type": "object",
            "properties": {
                "chosenSKU": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyPhone": {
            "type": "object",
            "properties": {
                "phone": {
                    "description": "Номер телефона для верификации",
                    "type": "string"
                }
            }
        },
        "dto.VerifyPhoneOTP": {
            "type": "object",
            "properties": {
                "otp": {
                    "description": "One-Time-Password отправленный по СМС",
                    "type": "string"
                },
                "phone": {
                    "description": "Номер телефона для верификации",
                    "type": "string"
                }
            }
        },
        "httperrors.Details": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "application-определенный код ошибки",
                    "type": "integer"
                },
                "message": {
                    "description": "application-level сообщение, для дебага",
                    "type": "string"
                },
                "status": {
                    "description": "сообщение пользовательского уровня",
                    "type": "string"
                }
            }
        },
        "httperrors.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/httperrors.Details"
                },
                "validation": {
                    "description": "ошибки валидации",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Address": {
            "type": "object",
            "properties": {
                "delivery": {
                    "type": "string",
                    "example": "track"
                },
                "pickupPoint": {
                    "type": "string",
                    "example": "Kurmangazy 77"
                }
            }
        },
        "models.Auto": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "about": {
                    "$ref": "#/definitions/models.LangOptions"
                },
                "brand": {
                    "$ref": "#/definitions/models.Brand"
                },
                "color": {
                    "$ref": "#/definitions/models.Color"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Media"
                    }
                },
                "price": {
                    "$ref": "#/definitions/models.Price"
                },
                "sku": {
                    "type": "string"
                },
                "title": {
                    "$ref": "#/definitions/models.LangOptions"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Brand": {
            "type": "object",
            "properties": {
                "equipment": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "$ref": "#/definitions/models.LangOptions"
                }
            }
        },
        "models.Color": {
            "type": "object",
            "properties": {
                "hex": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "$ref": "#/definitions/models.LangOptions"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "models.Contact": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "jon@mail.ru"
                },
                "mobileNumber": {
                    "type": "string",
                    "example": "87777777777"
                }
            }
        },
        "models.Customer": {
            "type": "object",
            "properties": {
                "contact": {
                    "$ref": "#/definitions/models.Contact"
                },
                "firstName": {
                    "type": "string",
                    "example": "Jon"
                },
                "lastName": {
                    "type": "string",
                    "example": "Bones"
                },
                "middleName": {
                    "type": "string",
                    "example": "Jones"
                },
                "taxCode": {
                    "type": "string",
                    "example": "832918392183"
                }
            }
        },
        "models.Goods": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "iphone"
                },
                "category": {
                    "type": "string",
                    "example": "smartphony"
                },
                "image": {
                    "type": "string",
                    "example": "https://cdn.dxomark.com/wp-content/uploads/medias/post-61183/iphone-12-pro-blue-hero.jpg"
                },
                "model": {
                    "type": "string",
                    "example": "12 PRO"
                },
                "price": {
                    "type": "string",
                    "example": "5000"
                }
            }
        },
        "models.LangOptions": {
            "type": "object",
            "properties": {
                "kz": {
                    "type": "string"
                },
                "ru": {
                    "type": "string"
                }
            }
        },
        "models.Media": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.Offer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_order_sum": {
                    "type": "integer"
                },
                "min_order_sum": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "partner_code": {
                    "type": "string"
                },
                "payment_type_group_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Offers": {
            "type": "object",
            "properties": {
                "contractNumber": {
                    "type": "string",
                    "example": "d12ed1"
                },
                "loanAmount": {
                    "type": "string",
                    "example": "144000"
                },
                "loanLength": {
                    "type": "string",
                    "example": "12"
                },
                "monthlyPayment": {
                    "type": "integer",
                    "example": 12000
                },
                "product": {
                    "type": "string",
                    "example": "rassrochka_12"
                },
                "productType": {
                    "type": "string",
                    "example": "installment"
                }
            }
        },
        "models.Order": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/models.Address"
                },
                "channel": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "customer": {
                    "$ref": "#/definitions/models.Customer"
                },
                "goods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Goods"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isDelivery": {
                    "type": "boolean"
                },
                "loanLength": {
                    "type": "string"
                },
                "orderState": {
                    "type": "string"
                },
                "paymentMethod": {
                    "type": "string"
                },
                "paymentPartners": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PaymentPartners"
                    }
                },
                "productType": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "redirectUrl": {
                    "type": "string"
                },
                "referenceId": {
                    "type": "string"
                },
                "salesPlace": {
                    "type": "string"
                },
                "systemCode": {
                    "type": "string"
                },
                "totalCost": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verificationId": {
                    "type": "string"
                },
                "verificationSmsCode": {
                    "type": "string"
                },
                "verificationSmsDateTime": {
                    "type": "string"
                }
            }
        },
        "models.PaymentPartners": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "mfo_airba"
                }
            }
        },
        "models.Price": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "minimum": {
                    "description": "Minimum is the minimum possible price for this product. Used for validation of merchant prices.",
                    "type": "integer"
                },
                "old": {
                    "type": "integer"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.UserApplication": {
            "type": "object",
            "properties": {
                "chosenSKU": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "api.test.somatic.dev",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "AutoCredit API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
